import { field, group } from '@nuxt/content/preview'

export default defineNuxtSchema({
  appConfig: {
    site: group({
      title: 'Site',
      description: 'Site configuration',
      icon: 'ph:info',
      fields: {
        name: field({
          type: 'string',
          title: 'Name',
          description: 'Site name, appearing at the top of your site.',
          icon: 'ph:caret-circle-right',
        }),
        description: field({
          type: 'string',
          title: 'Description',
          description: 'Site description.',
          icon: 'ph:paragraph',
        }),
        url: field({
          type: 'string',
          title: 'URL',
          description: 'Your website\'s canonical URL.',
          icon: 'ph:globe',
        }),
        copyright: field({
          type: 'string',
          title: 'Copyright',
          description: 'Copyright notice appearing in the footer of your website.',
          icon: 'ph:copyright',
        }),
        og: group({
          title: 'Open Graph',
          description: 'Settings for the Open Graph images generated by TNT.',
          icon: 'ph:image',
          fields: {
            component: field({
              type: 'string',
              title: 'Component',
              description: 'TNt OpenGraph component used to render your OG images.',
              icon: 'ph:image-square',
            }),
            website: field({
              type: 'string',
              title: 'Website',
              description: 'The hostname of your website, shown on OG images.',
              icon: 'ph:globe',
            }),
            color: field({
              type: 'string',
              title: 'Color',
              description: 'Background color for your OG images.',
              icon: 'ph:palette',
            }),
          }
        }),
      },
    }),
    ui: group({
      title: 'UI',
      description: 'Theme configuration',
      icon: 'ph:palette-fill',
      fields: {
        layout: field({
          type: 'string',
          title: 'Layout',
          description: 'The default layout to be used for your pages if no other value is provided.',
          icon: 'ph:layout',
          default: 'default',
          required: ['default', 'headerless', 'article', 'doc', 'empty']
        })
      }
    })
  }
})
