import { field, group } from '@nuxt/content/preview'

export default defineNuxtSchema({
  appConfig: {
    site: group({
      icon: 'ph:info',
      fields: {
        name: field({
          type: 'string',
          title: 'Name',
          description: 'Site name, appearing at the top of your site',
        }),
        description: field({
          type: 'string',
          title: 'Description',
          description: 'Site description',
        }),
        url: field({
          type: 'string',
          title: 'URL',
          description: 'Your website\'s canonical URL',
        }),
        og: group({
          title: 'Open Graph',
          description: 'Settings for the Open Graph images generated by TNT.',
          fields: {
            component: field({
              type: 'string',
              title: 'Component',
              description: 'OpenGraph component to be used for rendering',
              default: 'TntColor',
              required: ['TntColor', 'TntTestimonial']
            }),
            website: field({
              type: 'string',
              title: 'Website',
              description: 'OG Image website name',
            }),
            color: field({
              type: 'string',
              title: 'Color',
              description: 'OG Image background color',
            }),
          }
        }),
      },
    }),
    ui: group({
      icon: 'ph:palette',
      fields: {
        layout: field({
          type: 'string',
          title: 'Layout',
          description: 'Default page layout',
          default: 'default',
          required: ['default', 'headerless', 'article', 'doc', 'empty']
        }),
        theme: field({
          type: 'string',
          title: 'Theme',
          description: 'Base theme',
          default: 'solid',
          required: ['solid', 'ghost']
        }),
        pattern: field({
          type: 'string',
          title: 'Background Pattern',
          description: 'Hero Patterns by Steve Schoger',
          default: false,
          required: ['jigsaw', 'overcast', 'formal invitation', 'topography', 'texture', 'i like food', 'bubbles', 'floating cogs', 'glamorous', 'circuit board']
        }),
        colors: group({
          title: 'Colors',
          description: 'Theme colors',
          fields: {
            primary: field({
              type: 'string',
              title: 'Primary',
              description: 'Primary color used for links, buttons and interactivity',
              default: 'green',
              required: ['red', 'orange', 'amber', 'yellow', 'lime', 'green', 'emerald', 'teal', 'cyan', 'sky', 'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose'],
            }),
            secondary: field({
              type: 'string',
              title: 'Secondary',
              description: 'Secondary color (not currently used by TNT)',
              default: 'blue',
              required: ['red', 'orange', 'amber', 'yellow', 'lime', 'green', 'emerald', 'teal', 'cyan', 'sky', 'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose'],
            }),
            neutral: field({
              type: 'string',
              title: 'Neutral',
              description: 'Neutral color used for the site text, background and layout',
              default: 'slate',
              required: ['slate', 'gray', 'zinc', 'neutral', 'stone'],
            }),
          }
        })
      }
    }),
    header: group({
      icon: 'mdi:page-layout-header',
      fields: {
        navigation: group({
          title: 'Navigation',
          description: 'Links to be shown in the site header',
          fields: {
            content: field({
              type: 'boolean',
              title: 'Content navigation',
              description: 'If true, TNT will automatically generate navigation links based on your site contents',
              default: true,
            }),
            // TODO: With these values being what they are...
            //       These links could in fact be appended onto the generated list!
            //       We could have generated links AND additional links like to... Facebook, GitHub, whatever...
            links: field({
              type: 'array',
              title: 'Links',
              description: 'Links to be shown in the header',
              default: [],
            }),
          },
        }),
      },
    }),
    footer: group({
      icon: 'mdi:page-layout-footer',
      fields: {
        about: field({
          type: 'string',
          title: 'About',
          description: 'About text appearing in the footer of your website',
        }),
        contact: group({
          title: 'Contact',
          description: 'Contact details appearing in your site footer',
          fields: {
            email: field({
              type: 'string',
              title: 'Email',
              description: 'Contact email address',
            }),
            tel: field({
              type: 'string',
              title: 'Telephone',
              description: 'Contact telephone number',
            }),
            address: field({
              type: 'string',
              title: 'Address',
              description: 'Contact mailing or street address',
            }),
          }
        }),
        copyright: field({
          type: 'string',
          title: 'Copyright',
          description: 'Copyright notice appearing in the footer of your website',
        }),
        navigation: group({
          title: 'Navigation',
          description: 'Links to be shown in the site footer',
          fields: {
            content: field({
              type: 'boolean',
              title: 'Content navigation',
              description: 'If true, TNT will automatically generate navigation links based on your site contents',
              default: true,
            }),
            links: field({
              type: 'array',
              title: 'Links',
              description: 'Links to be shown in the footer',
              default: [],
            }),
          },
        }),
      },
    }),
  }
})
